services:
  db:
    image: postgres:16-alpine
    container_name: almoxarifado-usinagem-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-toolcrib}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-toolcrib}
      POSTGRES_DB: ${POSTGRES_DB:-toolcrib}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-toolcrib} -d ${POSTGRES_DB:-toolcrib}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    

  web:
    build: .
    container_name: almoxarifado-usinagem
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://toolcrib:toolcrib@db:5432/toolcrib}
      RUN_MIGRATIONS: "1"
      RUN_SEED: "1"
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
